### ISSUE TITLE
overriddenConfig перезаписывает поле message

### ISSUE THREAD

**Issue by paladosss** [wolframdeus/backend-template#1]
https://github.com/wolframdeus/backend-template/blob/7a23a42010a695aadb26a283ed812152895e3eb7/src/gql/utils/apollo.ts#L15

overriddenConfig по умолчанию перезаписывает поле message, следовательно поле всегда пустое

**Comment by wolframdeus** [comment]
Спасибо! Баг исправлен, залит в версии 1.3.5
