### ISSUE TITLE
I am the issue

### ISSUE THREAD

**Issue by WDIlsb** [wolframdeus/backend-template#3]
I need https for my app, but server starts only on http
<img width="446" alt="Снимок экрана 2020-06-12 в 14 56 49" src="https://user-images.githubusercontent.com/59749304/84500393-1c312280-acbd-11ea-8595-956a55a629c4.png">

**Comment by wolframdeus** [comment]
I am not sure, but probably it will be enough to replace [here](https://github.com/wolframdeus/backend-template/blob/master/src/http/runHttpServer.ts)

```import {createServer} from 'http';``` 

to

```import {createServer} from 'https';``` 

The reason I dont use https is most of the time, server stands behind Nginx web server which provides safe protocol. Moreover, when using https on Node server, it will make you generate certificates and set paths to them while creating https server. 

For test purposes you could use [tunnel](https://github.com/wolframdeus/backend-template/blob/master/package.json#L18) package script. It creates ngrok tunnel and returns https link you could use in your application. Usage:

`yarn tunnel 9000`

In production I strongly recommend using Nginx web server along with certbot (in case, you have no certificate).

**Comment by WDIlsb** [comment]
Thank you for the answer, you made a great job, I will be happy to see in the future some simple example of real app(back+front) made on this template. I think it will be very useful for many junior developers.

Best wishes, thanks again
